branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: jrcms
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.09.9-ce
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: null
  workspace_type: Application
